# Generated by Django 4.1.5 on 2023-01-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
            ],
            options={
                'ordering': ('order_id',),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
