# Generated by Django 4.1.5 on 2023-01-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
